### ISSUE TITLE
Reference star calibration missing in fitting scripts

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/SN-PWV#24]
Simulated light-curves in the fitting scripts are not calibrated relative to a reference star. This means fit results don't accurately represent what we expect to see with LSST.

**Comment by djperrefort** [comment]
As I work on this I'm realizing some thought needs to be put into how the PWV is specified when calibrating relative to a reference star. Specifically, we need to specify PWV values when **simulating** SN observations **and** when **calibrating** to a reference star(s). 

For the SN observations we interpolate a PWV value at Zenith and scale the value according to the airmass of the observation. This is straight forward because we know the datetime of the observation and the RA/Dec - thus giving is the airmass. I am happy with this approach.

Repeating the same process for the reference stars is more tricky since we don't have coordinates for the reference star(s). This means I can either 1) just use the value at zenith, or 2) look up a reference star catalogue and use those coordinates / stellar types.

**Comment by djperrefort** [comment]
Having thought about this overnight I'm leaning toward option 3, but am curious if @wmwv has thoughts on this.

**Comment by wmwv** [comment]
The reference stars are observed at the same time, in the same image.

Option 3.
